### ISSUE TITLE
TypeError: Cannot read property 'authParams' of undefined

### ISSUE THREAD

**Issue by Sieabah** [auth0/passport-auth0#106]
### Description

When trying to login with auth0-lock or a passport redirect it subsequently fails because express does not have session defined. 

This exact configuration works in 1.2.1.

### Reproduction

```
apiserver_1  | TypeError: Cannot read property 'authParams' of undefined
apiserver_1  |     at Auth0Strategy.Strategy.authenticate (/srv/app/node_modules/passport-auth0/lib/index.js:79:74)
apiserver_1  |     at attempt (/srv/app/node_modules/passport/lib/middleware/authenticate.js:361:16)
apiserver_1  |     at authenticate (/srv/app/node_modules/passport/lib/middleware/authenticate.js:362:7)
apiserver_1  |     at Promise (/srv/app/node_modules/@nestjs/passport/dist/auth.guard.js:83:3)
apiserver_1  |     at new Promise (<anonymous>)
apiserver_1  |     at /srv/app/node_modules/@nestjs/passport/dist/auth.guard.js:75:83
apiserver_1  |     at MixinAuthGuard.<anonymous> (/srv/app/node_modules/@nestjs/passport/dist/auth.guard.js:47:36)
apiserver_1  |     at Generator.next (<anonymous>)
apiserver_1  |     at /srv/app/node_modules/@nestjs/passport/dist/auth.guard.js:19:71
apiserver_1  |     at new Promise (<anonymous>)
apiserver_1  |     at __awaiter (/srv/app/node_modules/@nestjs/passport/dist/auth.guard.js:15:12)
apiserver_1  |     at MixinAuthGuard.canActivate (/srv/app/node_modules/@nestjs/passport/dist/auth.guard.js:40:20)
apiserver_1  |     at GuardsConsumer.tryActivate (/srv/app/node_modules/@nestjs/core/guards/guards-consumer.js:14:34)
apiserver_1  |     at canActivateFn (/srv/app/node_modules/@nestjs/core/router/router-execution-context.js:132:59)
apiserver_1  |     at /srv/app/node_modules/@nestjs/core/router/router-execution-context.js:41:37
apiserver_1  |     at /srv/app/node_modules/@nestjs/core/router/router-proxy.js:8:23
```

```
@Injectable()
export class Auth0Strategy extends PassportStrategy(Strategy) {
  constructor(
    private readonly authService: AuthService,
    private readonly configService: ConfigService,
  ) {
    super(
      {
        clientID: configService.get('auth.auth0.client_id'),
        domain: configService.get('auth.auth0.domain'),
        clientSecret: configService.get('auth.auth0.secret'),
        callbackURL: configService.get('auth.auth0.callback'),
        state: false,
        scope: configService.get('auth.scopes', []).join(' ')
      },
      async (accessToken, refreshToken, extraParams, profile, done) => {
        console.log(profile);
        try{
          const user = await this.authService.validateUser(profile);
          return done(null, user)
        } catch(e){
          return done(e);
        }
      }
    );

    serializeUser((user, done) => {
      done(null, user);
    });

    deserializeUser((user, done) => {
      done(null, user);
    });
  }
}
```

### Environment

> Please provide the following:

- **Version of this library used:** 1.3.1
- **Version of the platform or framework used, if applicable:** Nest.js/passport 6.1.0
- **Other relevant versions (language, server software, OS, browser):** node 10
- **Other modules/plugins/libraries that might be involved:** Nest.js

**Comment by davidpatrick** [comment]
This will happen when your `login` route is processing the request before your session middleware.  The correct order of middleware would be

```javascript
passport.use(auth0Strategy)
app.use(expressSession)
app.use(passport.initialize())
app.use(passport.session())
app.get('/login', passport.authenticate('auth0'), {}), function (req, res){})
```

You can reference https://github.com/auth0-samples/auth0-nodejs-webapp-sample/blob/master/01-Login/app.js if you need a working example

**Comment by Sieabah** [comment]
@davidpatrick I'll revisit this after the holidays but the nestjs framework handles things a little differently. If it's unsupported thats fine, I'll just migrate to using the providers directly. However this worked in 1.2.x and broke for 1.3.x so I'll version lock it to 1.2.1 for the time being.

**Comment by joshcanhelp** [comment]
Related to #107, fixed in #108

**Comment by afrancht** [comment]
Hello @joshcanhelp @davidpatrick I'm still having this issue despite being on version 1.3.2 as observed in @Sieabah 's code. He is trying to use passport-auth0 with state set to false. In that case it does not need for express to use the package express-sesison. I'm facing this issue when I remove express-session despite having aded { state: false } when declaring the new strategy.

Any help will be appreciated.
